export const queryKeys = {
  countries: ["countries"],
  country: (countryCode) => ["country", countryCode],
  borderCountries: (codes) => ["border-countries", codes],
  region: (region) => ["region", region],
  geocode: (query) => ["geocode", query],
  forecast: (lat, lng) => ["forecast", lat, lng],
  airQuality: (lat, lng) => ["air-quality", lat, lng],
  marine: (lat, lng) => ["marine", lat, lng],
  historicalWeather: (lat, lng, startDate, endDate, timezone = "auto") => [
    "historical-weather",
    lat,
    lng,
    startDate,
    endDate,
    timezone,
  ],
  climateProjection: (lat, lng, startDate, endDate, model) => [
    "climate-projection",
    lat,
    lng,
    startDate,
    endDate,
    model,
  ],
  nearbyEvents: (params = {}) => ["nearby-events", params],
  summary: (title) => ["summary", title],
  worldBank: (countryCode) => ["world-bank", countryCode],
};
